# Based on https://gohugo.io/hosting-and-deployment/hosting-on-github/
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # What does this do?
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: cache-${{ runner.os }}-nix-store-

      - name: Create a custom shell for devenv
        shell: bash
        run: |
          mkdir -p $HOME/.local/bin
          echo "#!/usr/bin/env bash" > $HOME/.local/bin/devenv
          echo "nix develop --command bash \"\$1\"" >> $HOME/.local/bin/devenv
          chmod +x $HOME/.local/bin/devenv

      - name: Build with Hugo
        shell: devenv {0}
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
